spring:
  app:
    tabs-dir: tabs/
  datasource:
    url: jdbc:postgresql://postgres:5432/tuneup_db # your database url
    username: admin # username for database 
    password: admin # password for database 
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      static-locations: file:tabsFiles/
  mail:
    host: smtp.gmail.com
    port: 587
    username: zaharkhachaturyan@gmail.com # usename for mail system 
    password: "hunzxtefaymbnayh" # password for mail system 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      url: redis://redis:6379 # your database url

jwt:
  secret: c2VjdXJlLWp3dC1rZXktaGVyZS1wbGVhc2UtYmUtY2FyZWZ1bA== # your secret
  accessExpirationMs: 3600000 # 1 час
  refreshExpirationMs: 604800000 # 7 дней
redis:
  url: redis://redis:6379 # your database url

# this is secret data I know, but I don't wanna lose them, and I guess nobody cares